packages:
  - apps/**
  - packages/**

catalog:
  '@sentry/nextjs': ^10.26.0
  '@supabase/auth-js': 2.87.0
  '@supabase/postgrest-js': 2.87.0
  '@supabase/realtime-js': 2.87.0
  '@supabase/supabase-js': 2.87.0
  '@types/node': ^22.0.0
  '@types/react': ^18.3.0
  '@types/react-dom': ^18.3.0
  next: ^15.5.9
  lodash: ^4.17.23
  lodash-es: ^4.17.23
  react: ^18.3.0
  react-dom: ^18.3.0
  recharts: ^2.15.4
  tailwindcss: 3.4.1
  tsx: 4.20.3
  typescript: ~5.9.0
  valtio: ^1.12.0
  vite: ^7.1.11
  vitest: ^3.2.0
  zod: ^3.25.76
