import type { WidgetInspectorConfig } from '../../types'
import { buildInspectorConfig } from '../fieldRegistry'

const fieldKeys = [
  'value',
  'placeholder',
  'label',
  'labelPosition',
  'labelAlign',
  'labelWidthValue',
  'labelWidthUnit',
  'labelCaption',
  'labelHide',
  'labelWrap',
  'prefix',
  'suffix',
  'prefixIcon',
  'suffixIcon',
  'tooltipText',
  'helperText',
  'labelCaptionColor',
  'labelFont',
  'labelTextColor',
  'labelRequiredIndicatorColor',
  'spellCheck',
  'enableBrowserAutofill',
  'autoFill',
  'autoCapitalize',
  'readOnly',
  'disabled',
  'showCharacterCount',
  'characterCountPosition',
  'loading',
  'formDataKey',
  'pattern',
  'regex',
  'minLength',
  'maxLength',
  'enforceMaxLength',
  'required',
  'customRule',
  'showClearButton',
  'hideValidationMessage',
  'maintainSpaceWhenHidden',
  'alwaysShowInEditMode',
  'showOnDesktop',
  'showOnMobile',
  'accentColor',
  'baseTextColor',
  'fontFamily',
  'hoverBackground',
  'inputBorderRadius',
  'inputBackground',
  'inputPlaceholderColor',
  'inputTextColor',
  'placeholderColor',
]

export const TextInputInspector: WidgetInspectorConfig = buildInspectorConfig(fieldKeys)
