import type { WidgetInspectorConfig } from '../../types'
import { buildInspectorConfig } from '../fieldRegistry'

const fieldKeys = [
  'value',
  'placeholder',
  'label',
  'rows',
  'autoResize',
  'minLines',
  'maxLines',
  'helperText',
  'labelHide',
  'labelPosition',
  'labelAlign',
  'labelWidthValue',
  'labelWidthUnit',
  'labelCaption',
  'labelWrap',
  'tooltipText',
  'labelCaptionColor',
  'labelFont',
  'labelTextColor',
  'labelRequiredIndicatorColor',
  'spellCheck',
  'enableBrowserAutofill',
  'autoFill',
  'autoCapitalize',
  'readOnly',
  'disabled',
  'showCharacterCount',
  'loading',
  'formDataKey',
  'pattern',
  'regex',
  'minLength',
  'maxLength',
  'enforceMaxLength',
  'required',
  'customRule',
  'hideValidationMessage',
  'maintainSpaceWhenHidden',
  'alwaysShowInEditMode',
  'showOnDesktop',
  'showOnMobile',
  'accentColor',
  'baseTextColor',
  'fontFamily',
  'hoverBackground',
  'inputBorderRadius',
  'inputBackground',
  'inputPlaceholderColor',
  'inputTextColor',
  'placeholderColor',
]

export const TextAreaInspector: WidgetInspectorConfig = buildInspectorConfig(fieldKeys, {
  value: {
    type: 'textarea',
    section: 'Content',
    placeholder: 'Default value',
  },
  rows: {
    min: 2,
    max: 20,
    step: 1,
  },
  minLines: {
    min: 1,
    max: 20,
    step: 1,
  },
  maxLines: {
    min: 1,
    max: 40,
    step: 1,
  },
})
